services:
  - type: web
    name: enlaces-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false  # Configura esto manualmente en el dashboard de Render
      - key: GOOGLE_CLIENT_SECRET
        sync: false  # Configura esto manualmente en el dashboard de Render
      - key: RENDER
        value: true  # Indica que está en entorno Render
    plan: free
